Allow non-exist source folder when it's optional
eclipse/buildship pull request #1197
Opened 2022-08-11 09:17 UTC by jdneo

Signed-off-by: sheche <sheche@microsoft.com>

Fixes #1196 

### Context

2022-08-23 14:56 UTC, donat requested changes
Looks good; I only have a couple of comments on the test coverage.

2022-08-23 14:56 UTC, donat commented on org.eclipse.buildship.core.test/src/main/groovy/org/eclipse/buildship/core/internal/workspace/SourceFolderUpdaterTest.groovy
> +	def "Optional source folders that don't physically exist are allowed."() {
Nit: please remove the trailing dot.

```suggestion
	def "Optional source folders that don't physically exist are allowed"() {
```

2022-08-23 14:56 UTC, donat commented on org.eclipse.buildship.core.test/src/main/groovy/org/eclipse/buildship/core/internal/workspace/SourceFolderUpdaterTest.groovy
> +		javaProject.rawClasspath.length == 1
Let's make the expectation a bit more concrete.

```suggestion
		javaProject.rawClasspath.length == 1
		javaProject.rawClasspath[0].entryKind == IClasspathEntry.CPE_SOURCE
                javaProject.rawClasspath[0].path.toPortableString() == "/project-name/src-not-there"
                javaProject.rawClasspath[0].extraAttributes as List == attributes(['optional': 'true']) as List
```

2022-08-24 13:59 UTC, merged

2022-08-24 14:00 UTC, donat commented
@jdneo Thank you for the contribution!

2022-08-25 01:37 UTC, jdneo commented
@donat Thank you too for reviewing and providing help 🎉