Add GradleProjectConfigurator to support smart-import
eclipse/buildship pull request #1219
Opened 2023-01-05 13:00 UTC by laeubi

Fixes https://github.com/eclipse/buildship/issues/356

### Context
Currently gradle projects are not detected when using smart import. This adds the necessary `ProjectConfigurator` to support importing gradle projects this way.

2023-01-05 15:01 UTC, laeubi commented
Build complain about 

>  Line does not match expected header line of '^ \* Copyright \(c\) \d\d\d\d Gradle Inc\.$'. [RegexpHeader]

but I do not have anything to do with `Gradle Inc` so why should they hold the copyright of my file?

2023-01-09 09:03 UTC, laeubi commented
@donat can you probably take a look at this? This will really improve user experience and preventing false positive detection in m2eclipse.

2023-03-09 08:05 UTC, donat commented
Sorry for the late reply. We'll take a look shortly.

2023-03-10 10:52 UTC, reinsch82 commented
@laeubi Would you mind rebasing your PR and changing the copyright line to 

  Gradle Inc. and others
  
This seems to be the recommended way of leaving the Copyright with it's original creators.

Feel free to add specific copyright notices somewhere down in the file, this was done in the past too.

2023-03-10 11:15 UTC, laeubi commented
Done.

2023-03-10 11:20 UTC, reinsch82 requested changes
Thanks for your contribution

2023-03-10 11:20 UTC, reinsch82 commented on org.eclipse.buildship.ui/src/main/java/org/eclipse/buildship/ui/internal/project/GradleProjectConfigurator.java
> +      if(new File(root, "gradle.properties").isFile()) {
its recommend best practice to use a [`settings` file](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:settings_file). 
`gradle.properties` is not required, although it is a reasonable indicator for a project.
I would suggest to at least also check for `settings.gradle` and `settings.gradle.kts`.

2023-03-10 11:20 UTC, reinsch82 commented on org.eclipse.buildship.ui/plugin.xml
> +				<hasFileRecursively filename="gradle.properties"/>
see comment on `isGradleRoot`

2023-03-10 11:52 UTC, reinsch82 commented
@laeubi you'll need to rebase again shortly, we had to change our copyrights too to match the new rule.
For some reason the PR would let it through
thx for your help

2023-03-10 12:01 UTC, laeubi commented
@reinsch82 I have adjusted the "marker files", also feel free to enhance this as needed afterwards, this is more a first start to make it work, but you as the gradel experts might have some ideas how to further improve that, I'm only a (seldom) gradle user so most of the time :-)

2023-03-13 09:36 UTC, donat approved these changes

2023-03-13 09:36 UTC, donat commented on org.eclipse.buildship.ui/plugin.xml
> +               <hasFileRecursively filename="settings.gradles"/>
❌ 

```suggestion
               <hasFileRecursively filename="settings.gradle"/>
```

2023-03-13 09:41 UTC, donat approved these changes

2023-03-13 09:41 UTC, donat commented on org.eclipse.buildship.ui/src/main/java/org/eclipse/buildship/ui/internal/project/GradleProjectConfigurator.java
> + * Copyright (c) 2019 Gradle Inc. and others.
```suggestion
 * Copyright (c) 2019 Gradle Inc. and others
```

2023-03-13 14:07 UTC, merged

2023-03-13 14:07 UTC, donat commented
Thank you for the contribution

2023-03-15 23:29 UTC, jabby commented
Thank you @laeubi

2023-03-16 05:24 UTC, laeubi commented
Great to see this integrated, will this be part of the next Eclipse Release (2023-06) or are there usually release in between?

2023-03-16 12:29 UTC, donat commented
We're planning to do a release in the upcoming weeks, so you can expect your changes to appear in Eclipse 2023-06 by default.